### ISSUE TITLE
Proxy doesn't reload when changing IP

### ISSUE THREAD

**Issue by mobilegmYT** [MCPI-Revival/MCPIL#15]
When you open mcpil, and change the server ip in the multiplayer tab, then launch mcpi, no servers show up. You have to close mcpil then reopen it for the proxy to connect.

**Comment by leha-code** [comment]
Ok. Ill try to fix this with a relod button

**Comment by leha-code** [comment]
I t s happening because of the proxy running from a file wih ip. Mcpil changes it, but he proxy is still rinnonh ith he old ip. You will need to stop the proksi and rerun it

**Comment by leha-code** [comment]
This isnt fxed yet so...

**Comment by TheBrokenRail** [comment]
This is fixed in 0.1.9. I tested it extensively.
