### ISSUE TITLE
the proxy is delaying the start of the  launcher

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/MCPIL#19]
Also when the internet is off it takes eve n longer! Ill try to fix this with a check of internet connection. I think that happens because the proxy is tryng to connect to the server.

**Comment by Alvarito050506** [comment]
I'm not 100% sure, but as far as I know, the proxy does not delay the Launcher at start, since it's another thread.

**Comment by mobilegmYT** [comment]
Closing since fix added in https://github.com/MCPI-Revival/proxy/commit/af94a84f71dfc5dcec134e33c6184de57a132b8c.
