### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MrRKernelPanic** [MCPI-Revival/MCPIL#29]
**Describe the bug**
When installed from PiApps and the MCPIL launcher run it error on load....
the main.log shows this..
```
Pulling minecraft-pi (thebrokenrail/minecraft-pi-reborn:client)...
client: Pulling from thebrokenrail/minecraft-pi-reborn
open /var/lib/docker/tmp/GetImageBlob239991661: no such file or directory

```
The folder it is looking for in tmp is empty.

If tried manually installing on a Pi4 Debian Buster (updated as instructions) when trying to install the .deb package
sudo dpkg -i minecraft-pi-reborn-native_1.0.0.20210228.2107_all.deb

I get
Error: No such image: thebrokenrail/minecraft-pi-reborn:client

It can't seem to connect / find the site.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian Buster (32bit)
 - MCPIL Version [e.g. 0.1.9]

**Comment by MrRKernelPanic** [comment]
Nevermind, i think this was either a Pi-Hole or Docker issue.  A reboot seemed to sort it.

**Comment by leha-code** [comment]
Idk why u used pi hole
