### ISSUE TITLE
How can i help?

### ISSUE THREAD

**Issue by dontbanmeplz** [MCPI-Revival/MCPIL#31]
This looks like an interesting project... How can i help

**Comment by Alvarito050506** [comment]
Hello! Thanks for your interest!

Currently we're trying to migrate from this to [gMCPIL](https://github.com/MCPI-Revival/gMCPIL) or [jMCPIL](https://github.com/MCPI-Revival/jMCPIL), so while any contribution would be welcome, focusing inother projects would be ideal. Some of our projects need a considerable amout of help, like [mcbes](https://github.com/MCPI-Revival/mcbes). We have a Discord [server](https://discord.gg/DCwcpyf) for faster communication and some info about out projects if you want to join, it's also a nice place to talk with the community.

Again, thanks for the interest in the project!

**Comment by leha-code** [comment]
U look good to replace me!

**Comment by RealCreepi** [comment]
@leha-code Are you really that angry for getting demoted? If you still don't get it: We disagree with your design philosophy. And either way the cold heart truth is that we are not looking to replace you since no new gap formed after your demotion...

**Comment by dontbanmeplz** [comment]
What is going on?

**Comment by nobody5050** [comment]
Inter-project drama, best to just ignore it :)

**Comment by donnerkebab1730** [comment]
idk seems kinda sus ngl

**Comment by leha-code** [comment]
> @leha-code Are you really that angry for getting demoted? If you still don't get it: We disagree with your design philosophy. And either way the cold heart truth is that we are not looking to replace you since no new gap formed after your demotion...

Whatcha talking bout? I haven't been in discord since five years or something!

**Comment by dontbanmeplz** [comment]
STFU DO IT ON DISCORD

**Comment by mobilegmYT** [comment]
Closing as issue is getting off-topic and it has been answered. Drama goes in the server, not on github.

**Comment by leha-code** [comment]
Wat

**Comment by dontbanmeplz** [comment]
It means go away basicly

**Comment by leha-code** [comment]
And u thought I was gonna go to discord

**Comment by donnerkebab1730** [comment]
rip

**Comment by nobody5050** [comment]
Locked as too heated.
