### ISSUE TITLE
Can't Craft in Minecraft without Touch GUI

### ISSUE THREAD

**Issue by GabeCoder** [MCPI-Revival/MCPIL#33]
**Describe the bug**
So whenever I play Minecraft without the touch GUI, for some reason, I can't craft anything without a crafting table, since the "Craft" button doesn't appear when I open my inventory. Even with an item to use in crafting, I can't somehow find the "Craft" button on the screen.

**To Reproduce**
1. Chop down a tree
2. Open the inventory
3. Look for the "Craft" button
**Expected behavior**
Crafting is a very essential part of Minecraft and is even included in the game's title. Without crafting, it is impossible to build houses out of wooden planks and prevents you from using tools to continue on with the game.

**Screenshots**
Here is a screenshot of the missing "Craft" button.
![Minecraft](https://user-images.githubusercontent.com/72320038/111669643-623b8980-87ed-11eb-94ed-e525a2a4d57e.png)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS
 - MCPIL Version 0.1.9

**Additional context**
Although there is nothing else wrong with the touch GUI, I recommend the health bar be placed on top of the items bar for a more desktop experience for Minecraft.

**Comment by mobilegmYT** [comment]
As vanilla MCPI does not include survival, it doesn't have the crafting gui. You must use the touch GUI for crafting and inventory support. It would also be very hard to change the positions of gui elements and to also add sound effects without a copyrit strike from mojang.

**Comment by GabeCoder** [comment]
> As vanilla MCPI does not include survival, it doesn't have the crafting gui. You must use the touch GUI for crafting and inventory support. It would also be very hard to change the positions of gui elements and to also add sound effects without a copyrit strike from mojang.

Understandable. Have a great day.

**Comment by GabeCoder** [comment]
Although, I still recommend the health bar on top of the hotbar for the No Touch GUI since it adds up to the Minecraft desktop experience.

**Comment by mobilegmYT** [comment]
> Although, I still recommend the health bar on top of the hotbar for the No Touch GUI since it adds up to the Minecraft desktop experience.

@TheBrokenRail might know how to do it, but it'll take a lot of work to change the function code.

**Comment by GabeCoder** [comment]
> > Although, I still recommend the health bar on top of the hotbar for the No Touch GUI since it adds up to the Minecraft desktop experience.
> 
> @TheBrokenRail might know how to do it, but it'll take a lot of work to change the function code.

Hmm, okay. Imma join his server to see what up.

**Comment by GabeCoder** [comment]
Fun fact: You can also control Minecraft with a console controller, like the console is an Xbox.
