### ISSUE TITLE
ttk themes is not availabe in rpis repos

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/MCPIL#35]
Maybe change smething incontrol?? It works though wih the source, with the themes installed via pip. That is wht 0.2.0rc1 refused to install even with. Pip.

**Comment by seaniedan** [comment]
Here's the error I get:

pi@pi4:~/MCPIL $ sudo dpkg -i out/mcpil_0.2.0-rc1-11-g224f00d_all.deb
Selecting previously unselected package mcpil.
(Reading database ... 98660 files and directories currently installed.)
Preparing to unpack .../mcpil_0.2.0-rc1-11-g224f00d_all.deb ...
Unpacking mcpil (0.2.0-rc1-11-g224f00d) ...
dpkg: dependency problems prevent configuration of mcpil:
 mcpil depends on python3-ttkthemes; however:
  Package python3-ttkthemes is not installed.
 mcpil depends on minecraft-pi-reborn-virgl | minecraft-pi-reborn-native; however:
  Package minecraft-pi-reborn-virgl is not installed.
  Package minecraft-pi-reborn-native is not installed.

dpkg: error processing package mcpil (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Errors were encountered while processing:
 mcpil


I try to install python3-ttkthemes

pi@pi4:~/MCPIL $ sudo apt install python3-ttkthemes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-ttkthemes is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-ttkthemes' has no installation candidate

I try to install ttkthemes
pi@pi4:~/MCPIL $ sudo apt install ttkthemes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ttkthemes

**Comment by mobilegmYT** [comment]
> Maybe change smething incontrol?? It works though wih the source, with the themes installed via pip. That is wht 0.2.0rc1 refused to install even with. Pip.

MCPIL is to be replaced by jMCPIL very soon so the 0.2 release is basically cancelled.

**Comment by seaniedan** [comment]
So .. I'm confused. Nothing works? 'change smething incontrol??' - can you be more specific? I don't understand the rest of your comment. I just want to play minecraft full screen.

**Comment by mobilegmYT** [comment]
> So .. I'm confused. Nothing works? 'change smething incontrol??' - can you be more specific? I don't understand the rest of your comment. I just want to play minecraft full screen.

I recommend using 0.1.9 and not 0.2.0

**Comment by Alvarito050506** [comment]
> So .. I'm confused. Nothing works? 'change smething incontrol??' - can you be more specific? I don't understand the rest of your comment. I just want to play minecraft full screen.

@seaniedan As you can see in the releases section, 0.2.0 is a pre-release, so using 0.1.9 is recommended for stability, and as @mobilegmYT said, this version of MCPIL is going to be replaced by [jMCPIL](https://github.com/MCPI-Revival/jMCPIL) and/or [gMCPIL](https://github.com/MCPI-Revival/gMCPIL) soon. You can try these versions which are meant to be even more stable and have less dependencies.

**Comment by seaniedan** [comment]
OK.. as for now, I try to install 0.19 and it fails:

pi@pi4:~ $ sudo dpkg -i mcpil_0.1.9_all.deb 
dpkg: warning: downgrading mcpil from 0.2.0-rc1-11-g224f00d to 0.1.9
(Reading database ... 98676 files and directories currently installed.)
Preparing to unpack mcpil_0.1.9_all.deb ...
Unpacking mcpil (0.1.9) over (0.2.0-rc1-11-g224f00d) ...
dpkg: dependency problems prevent configuration of mcpil:
 mcpil depends on minecraft-pi-reborn-virgl | minecraft-pi-reborn-native; however:
  Package minecraft-pi-reborn-virgl is not installed.
  Package minecraft-pi-reborn-native is not installed.

dpkg: error processing package mcpil (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Errors were encountered while processing:
 mcpil

**Comment by mobilegmYT** [comment]
> OK.. as for now, I try to install 0.19 and it fails:
> 
> pi@pi4:~ $ sudo dpkg -i mcpil_0.1.9_all.deb
> dpkg: warning: downgrading mcpil from 0.2.0-rc1-11-g224f00d to 0.1.9
> (Reading database ... 98676 files and directories currently installed.)
> Preparing to unpack mcpil_0.1.9_all.deb ...
> Unpacking mcpil (0.1.9) over (0.2.0-rc1-11-g224f00d) ...
> dpkg: dependency problems prevent configuration of mcpil:
> mcpil depends on minecraft-pi-reborn-virgl | minecraft-pi-reborn-native; however:
> Package minecraft-pi-reborn-virgl is not installed.
> Package minecraft-pi-reborn-native is not installed.
> 
> dpkg: error processing package mcpil (--install):
> dependency problems - leaving unconfigured
> Processing triggers for gnome-menus (3.31.4-3) ...
> Processing triggers for desktop-file-utils (0.23-4) ...
> Processing triggers for mime-support (3.62) ...
> Errors were encountered while processing:
> mcpil

Here use this video: https://www.youtube.com/watch?v=crDP_hpnUoo

**Comment by seaniedan** [comment]
I uninstalled this with 
```
sudo apt update; sudo apt full-upgrade -y
sudo apt --fix-broken install
sudo apt purge mcpil -y and sudo apt clean; sudo apt autoremove -y; sudo apt autoclean
```
and installed [pi-apps](https://github.com/Botspot/pi-apps) as per the video.

Thank you for your help, I look forward to your upcoming releases!
