### ISSUE TITLE
Gamer's SMP

### ISSUE THREAD

**Issue by GabeCoder** [MCPI-Revival/MCPIL#36]
**GRAND OPENING**
I have just begun hosting a server by the name: **Gamer's SMP**, a server where every player has a goal to survive together.
This server is to run from 10 AM to 10 PM ET, so for 12 hours, players have the opportunity to build together, fight together, and of course, play together.

The server's IP address is ```96.245.75.18```. (Isn't Minecraft just beautiful?)

Port is, of course, 19132.
Have fun!

Oh, I just forgot!
**Rules:**
1. No Griefing
2. No Swearing
3. No Abusing Glitches (Unless it doesn't affect other players)
4. This is not anarchy. This means that you must abide by the rules.

**Comment by mobilegmYT** [comment]
> **GRAND OPENING**
> I have just begun hosting a server by the name: **Gamer's SMP**, a server where every player has a goal to survive together.
> This server is to run from 10 AM to 10 PM ET, so for 12 hours, players have the opportunity to build together, fight together, and of course, play together.
> 
> The server's IP address is **172.17.0.1 **. It was opened on a Fios router. (Isn't Minecraft just beautiful?)
> 
> Port is, of course, 19132.
> Have fun!
> 
> Oh, I just forgot!
> **Rules:**
> 
> 1. No Griefing
> 2. No Swearing
> 3. No Abusing Glitches (Unless it doesn't affect other players)
> 4. This is not anarchy. This means that you must abide by the rules.

I assume you mean you'd like the server to be added to [mcpi.tk/servers](url). Just 1 slight issue, your server isn't port forwarded and you need to give us your public IP, not your private one.

**Comment by GabeCoder** [comment]
> > **GRAND OPENING**
> > I have just begun hosting a server by the name: **Gamer's SMP**, a server where every player has a goal to survive together.
> > This server is to run from 10 AM to 10 PM ET, so for 12 hours, players have the opportunity to build together, fight together, and of course, play together.
> > The server's IP address is **172.17.0.1 **. It was opened on a Fios router. (Isn't Minecraft just beautiful?)
> > Port is, of course, 19132.
> > Have fun!
> > Oh, I just forgot!
> > **Rules:**
> > 
> > 1. No Griefing
> > 2. No Swearing
> > 3. No Abusing Glitches (Unless it doesn't affect other players)
> > 4. This is not anarchy. This means that you must abide by the rules.
> 
> I assume you mean you'd like the server to be added to [mcpi.tk/servers](url). Just 1 slight issue, your server isn't port forwarded and you need to give us your public IP, not your private one.

Made that mistake. I fixed it.

**Comment by mobilegmYT** [comment]
@GabeCoder Done: https://mcpi.tk/servers

**Comment by GabeCoder** [comment]
**UPDATE:** The schedule has been changed to 12PM to 9 PM ET, due to my regular daily schedule.

**Comment by GabeCoder** [comment]
Farts, I just forgot to tell you that the player limit is 10 players.

**Comment by mobilegmYT** [comment]
> Farts, I just forgot to tell you that the player limit is 10 players.

https://github.com/MCPI-Revival/mcpi-revival.github.io/commit/8aa61a80caa5fee4b43d32e6891ea36e119ddd2c
