### ISSUE TITLE
NEWS:  Blocky Criminal on the Loose!

### ISSUE THREAD

**Issue by GabeCoder** [MCPI-Revival/MCPIL#38]
In TheBrokenRail's SMP (Survival Multiplayer), an unidentified wrongdoer has been suspected of stealing player's items and griefing their houses! While their identity remains unknown, please keep aware of any looters or griefers anywhere.

**Comment by mobilegmYT** [comment]
> In TheBrokenRail's SMP (Survival Multiplayer), an unidentified wrongdoer has been suspected of stealing player's items and griefing their houses! While their identity remains unknown, please keep aware of any looters or griefers anywhere.

1) Please use the github issues feature for it's intended purpose, not to spam or abuse it.
2) This is the github repo for MCPIL Launcher and this topic is unrelated
3) This isn't a news broadcasting station 😆 
4) Perhaps you might be interested in joining our discord server here: [](https://discord.com/invite/aDqejQGMMy), which has channels for users to talk with other players about in-game stuff and so on (It's free to use Discord BTW).

**Comment by GabeCoder** [comment]
> > In TheBrokenRail's SMP (Survival Multiplayer), an unidentified wrongdoer has been suspected of stealing player's items and griefing their houses! While their identity remains unknown, please keep aware of any looters or griefers anywhere.
> 
> 1. Please use the github issues feature for it's intended purpose, not to spam or abuse it.
> 2. This is the github repo for MCPIL Launcher and this topic is unrelated
> 3. This isn't a news broadcasting station 😆
> 4. Perhaps you might be interested in joining our discord server here: , which has channels for users to talk with other players about in-game stuff and so on (It's free to use Discord BTW).

k

**Comment by leha-code** [comment]
Okay... Maybe I did forget to change my status...

**Comment by leha-code** [comment]
Nah it's not me lol

**Comment by TheBrokenRail** [comment]
Locked.
