### ISSUE TITLE
Question: Data folder location?

### ISSUE THREAD

**Issue by GabeCoder** [MCPI-Revival/MCPIL#39]
So I was curious about where the Minecraft Pi texture files were so I could learn more about modding.
The question is, where is the folder with all the textures? Is it in an operating system folder?

**Comment by GabeCoder** [comment]
Sorry for posting these issues very often. I'll put a cooldown here.

**Comment by mobilegmYT** [comment]
> So I was curious about where the Minecraft Pi texture files were so I could learn more about modding.
> The question is, where is the folder with all the textures? Is it in an operating system folder?

The mods and texture packs use a overrides system, documented at https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-reborn/src/branch/master/docs/OVERRIDING_ASSETS.md. If you want to ask questions, I beg you to join the discord where it's easier for the both of us lol.
