### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by seaniedan** [MCPI-Revival/MCPIL#43]
**Describe the bug**
Cannot install

**To Reproduce**

I try to install the .deb file:
pi@pi4:~/MCPIL $ sudo dpkg -i out/mcpil_0.2.0-rc1-11-g224f00d_all.deb
Selecting previously unselected package mcpil.
(Reading database ... 98660 files and directories currently installed.)
Preparing to unpack .../mcpil_0.2.0-rc1-11-g224f00d_all.deb ...
Unpacking mcpil (0.2.0-rc1-11-g224f00d) ...
dpkg: dependency problems prevent configuration of mcpil:
 mcpil depends on python3-ttkthemes; however:
  Package python3-ttkthemes is not installed.
 mcpil depends on minecraft-pi-reborn-virgl | minecraft-pi-reborn-native; however:
  Package minecraft-pi-reborn-virgl is not installed.
  Package minecraft-pi-reborn-native is not installed.

dpkg: error processing package mcpil (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.31.4-3) ...
Processing triggers for desktop-file-utils (0.23-4) ...
Processing triggers for mime-support (3.62) ...
Errors were encountered while processing:
 mcpil

I try to install the dependencies:

pi@pi4:~/MCPIL $ sudo apt install minecraft-pi-reborn-virgl minecraft-pi-reborn-native
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package minecraft-pi-reborn-virgl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package minecraft-pi-reborn-native is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'minecraft-pi-reborn-virgl' has no installation candidate
E: Package 'minecraft-pi-reborn-native' has no installation candidate

**Expected behavior**
I want to see the screenshot of the minecraft GUI
 

**Desktop (please complete the following information):**
 - OS: Raspbian 32 bit on pi4 8GB

**Comment by mobilegmYT** [comment]
https://github.com/MCPI-Revival/MCPIL/issues/35#issuecomment-807296311
