### ISSUE TITLE
Can't install MCPIL from .deb file and broken code

### ISSUE THREAD

**Issue by robtech21** [MCPI-Revival/MCPIL#47]
I have some issues:

1. The package python3-ttkthemes doesn't exist, period.
2. We broke the launcher script, probably through the date-determined splashes/titles

You might want to:
1. Fix the dependencies
2. Roll the release back to before the April Fools' title swap update if possible

**Comment by mobilegmYT** [comment]
1. Yea... might have to ask @TheBrokenRail about the ttk stuff, but we're merging jmcpil or gmpcil here soon so probably doesn't matter since everyone uses the 0.1.9 release still
2. I think https://github.com/MCPI-Revival/MCPIL/pull/48 fixed it

**Comment by robtech21** [comment]
> 1. Yea... might have to ask @TheBrokenRail about the ttk stuff, but we're merging jmcpil or gmpcil here soon so probably doesn't matter since everyone uses the 0.1.9 release still
> 2. I think #48 fixed it

ah okay

**Comment by robtech21** [comment]
I'm just gonna close this...
