### ISSUE TITLE
[Feature Request] Add desktop icon

### ISSUE THREAD

**Issue by mobilegmYT** [MCPI-Revival/MCPIL#55]
MCPIL doesn't have a icon in taskbar/window for me on xfce4/twisterOS. Add one maybe? (Also we sorta need this along with mcpirdl to be added to TwisterOS)

**Comment by Alvarito050506** [comment]
Ok but... Don't add mcpirdl or MCPIL to TwisterOS. We will have official Dockerless builds (and a new MCPIL) soon:tm:

**Comment by mobilegmYT** [comment]
> Ok but... Don't add mcpirdl or MCPIL to TwisterOS. We will have official Dockerless builds (and a new MCPIL) soon™️

Well yea duh, but still would be nice to have the icon added before the big switch.

**Comment by mobilegmYT** [comment]
Added in https://github.com/MCPI-Revival/MCPIL/commit/3bbb2c7026e09e8ea13958566b1acd43ed2931d9
