### ISSUE TITLE
[Bug] Can't connect to servers

### ISSUE THREAD

**Issue by Zipperoos** [MCPI-Revival/MCPIL#56]
**Describe the bug**
I can't connect to any servers, not even the default server (`thebrokenrail.com`). The only thing I have done was crash my pi and reinstall the os, but everything else is working just as before.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Raspbian]
 - MCPIL Version [e.g. 0.2.0]

**Additional context**

**Comment by Alvarito050506** [comment]
Hey! Please provide the following info:
 + MCPIL Version
 + OS name and version
 + RPi model
 + From where did you install MCPIL?
 + Are you sure your RPi's crash is related to this bug?
 
 Thanks!

**Comment by Zipperoos** [comment]
NVM Im sry for whatever reason it fixed itself. Thx for being so
prompt to respond!

~Zipperoos

**Comment by Alvarito050506** [comment]
No problem at all! Good thing it's fixed now. :-)

**Comment by donnerkebab1730** [comment]
bruh im having the same issues

**Comment by donnerkebab1730** [comment]
even after opening and closing + uninstalling and reinstalling

**Comment by donnerkebab1730** [comment]
also hi #git-webhooks!

**Comment by Alvarito050506** [comment]
Hm, reopening then... Could you describe your issue with more detail?

**Comment by donnerkebab1730** [comment]
im not sure what to say really i just put the ip in and the port then it just wont work

**Comment by Alvarito050506** [comment]
Hmm :thinking: Are you running a server or another MCPI instance in your RPi already?

**Comment by leha-code** [comment]
Try running the proxy from a terminal

**Comment by donnerkebab1730** [comment]
> Hmm 🤔 Are you running a server or another MCPI instance in your RPi already?


nope

**Comment by Zipperoos** [comment]
The funny thing is that it fixed itself. IDK what I did, or if I even
DID anything.

**Comment by donnerkebab1730** [comment]
Same thing has happened to me before except this time it has t fixed itself

**Comment by TheBrokenRail** [comment]
I would say 99% chance this is just a result of ``thebrokenrail.com`` not being up 24/7.

**Comment by Alvarito050506** [comment]
Ah, ok, closing this.

**Comment by Zipperoos** [comment]
XD I'm such an idiot that would make sense especially since
thebrokenrail has been quite bugged lately....

**Comment by mobilegmYT** [comment]
> XD I'm such an idiot that would make sense especially since thebrokenrail has been quite bugged lately....

I also run my own server `pbptanarchy.tk` if you'd like to play on it.

**Comment by Zipperoos** [comment]
Oooh! How do you host servers for the Pi edition?

~Zipperoos

**Comment by mobilegmYT** [comment]
> Oooh! How do you host servers for the Pi edition? ~Zipperoos

https://mcpirevival.tk/howto/creating-servers.html

**Comment by Zipperoos** [comment]
TYSM I have now hosted server at 192.168.254.15

**Comment by Alvarito050506** [comment]
Hi! There's a problem with that: it's your private IP (i.e.: only people in your network can see it). You would need to do port forwarding and some magic to expose it to the internet.

Anyways, this is getting off-topic, I would recommend you joining our [Discord server](https://discord.gg/DCwcpyf) for more general support.

**Comment by Zipperoos** [comment]
Ahhh thx will do

**Comment by donnerkebab1730** [comment]
> Ah, ok, closing this.

- Bruh my servers are still broken:(

But I'm trying gmcpil instead

**Comment by Zipperoos** [comment]
Gmcpil?
~Zipperoos

**Comment by Alvarito050506** [comment]
[gMCPIL](https://github.com/MCPI-Revival/gMCPIL) is one of the proposed replacements for MCPIL, written on C, based on GTK+ 3. The other one is [jMCPIL](https://github.com/MCPI-REvival/jMCPIL), written in Java using Swing.

Please join our Discord server for further discussion, so this doesn't become too off-topic.

**Comment by TheBrokenRail** [comment]
Locked.
